version: '3.8'

services:
  claude-code:
    build:
      context: .
      dockerfile: Dockerfile.simple
      args:
        USER_UID: ${HOST_UID:-1000}
        USER_GID: ${HOST_GID:-1000}
        USERNAME: developer
    container_name: claude-code-dev
    hostname: claude-code-dev
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      - CLAUDE_CONFIG_DIR=/home/developer/.claude
      - TERM=xterm-256color
      - SHELL=/bin/zsh
    volumes:
      # No host repos mounted - container will use fresh clones

      # Mount host shell config (read-only)
      - type: bind
        source: ${HOME}/.zshrc
        target: /host-config/.zshrc
        read_only: true

      # Mount host SSH config (read-only) for git operations
      - type: bind
        source: ${HOME}/.ssh
        target: /home/developer/.ssh
        read_only: true

      # Mount host git config (read-only)
      - type: bind
        source: ${HOME}/.gitconfig
        target: /home/developer/.gitconfig
        read_only: true

      # Named volume for Claude Code configuration (isolated)
      - claude-code-config:/home/developer/.claude

      # Named volume for command history persistence
      - claude-code-history:/home/developer/.zsh_history_persistent

      # Optional: Mount additional config directories
      - type: bind
        source: ${HOME}/.npmrc
        target: /home/developer/.npmrc
        read_only: true

    working_dir: /workspace
    restart: unless-stopped

volumes:
  claude-code-config:
    driver: local
  claude-code-history:
    driver: local